// GENERATED by backend/bench/build-reference.mjs from backend/bench/results/*.json. Do not edit by hand.
export const REFERENCE = {
  "measuredOn": "2026-09-30",
  "faults": {
    "sample": [
      "stress-03",
      "stress-07",
      "stress-09"
    ],
    "rows": [
      {
        "injected": "bad_stt",
        "predicted": [
          "bad_stt",
          "bad_stt",
          "bad_stt"
        ]
      },
      {
        "injected": "tts_glitch",
        "predicted": [
          "tts_glitch",
          "tts_glitch",
          "tts_glitch"
        ]
      },
      {
        "injected": "timeout",
        "predicted": [
          "timeout",
          "timeout",
          "timeout"
        ]
      },
      {
        "injected": "user_hangup",
        "predicted": [
          "user_hangup",
          "user_hangup",
          "user_hangup"
        ]
      },
      {
        "injected": "network_drop",
        "predicted": [
          "network_drop",
          "network_drop",
          "network_drop"
        ]
      },
      {
        "injected": "exception",
        "predicted": [
          "exception",
          "exception",
          "exception"
        ]
      },
      {
        "injected": "hallucination",
        "predicted": [
          "timeout",
          "ok",
          "timeout"
        ]
      }
    ]
  },
  "clean": {
    "n": 19,
    "ok": 18,
    "other": [
      {
        "id": "noisy-line",
        "predicted": "bad_stt"
      }
    ]
  },
  "cost": {
    "n": 19,
    "avgUsd": 0.004077368421052632,
    "minUsd": 0.00151,
    "maxUsd": 0.00674
  },
  "stages": [
    {
      "stage": "stt",
      "provider": "deepgram",
      "n": 155,
      "p50Ms": 805,
      "p95Ms": 1467,
      "maxMs": 1930
    },
    {
      "stage": "stt",
      "provider": "whisper",
      "n": 27,
      "p50Ms": 1210,
      "p95Ms": 2800,
      "maxMs": 3890
    },
    {
      "stage": "llm",
      "provider": "openai",
      "n": 182,
      "p50Ms": 1035,
      "p95Ms": 1834,
      "maxMs": 3835
    },
    {
      "stage": "tts",
      "provider": "openai",
      "n": 182,
      "p50Ms": 1718,
      "p95Ms": 2808,
      "maxMs": 3975
    }
  ],
  "costStages": [
    {
      "stage": "stt",
      "provider": "deepgram",
      "n": 155,
      "avgCostUsd": 0.0016593
    },
    {
      "stage": "llm",
      "provider": "openai",
      "n": 182,
      "avgCostUsd": 0.0000413
    },
    {
      "stage": "tts",
      "provider": "openai",
      "n": 182,
      "avgCostUsd": 0.0019381
    },
    {
      "stage": "analysis",
      "provider": "openai",
      "n": 142,
      "avgCostUsd": 0.0004077
    }
  ],
  "ab": {
    "sample": "call-1-clean-baseline.wav",
    "iterations": 3,
    "configA": {
      "llmModel": "gpt-4o-mini",
      "preferredSttProvider": "deepgram"
    },
    "configB": {
      "llmModel": "gpt-4o",
      "preferredSttProvider": "whisper"
    },
    "headline": "Config A is faster and cheaper, with no quality difference.",
    "winner": "A",
    "caveats": [],
    "a": {
      "n": 3,
      "failed": 0,
      "failureRate": 0,
      "avgCostUsd": 0.003581229166666667,
      "totalCostUsd": 0.010743687500000002,
      "avgLatencyS": 4.126333333333333,
      "avgWordErrorRate": 0,
      "avgSttConfidence": 0.9990160387878788,
      "failoverCount": 0,
      "sampleTranscript": "Hi. I'm calling because I was charged twice for the same order. It's order 48213, and I was charged $47.99 both times. Could you please check the transaction and refund the duplicate charge?",
      "primaryIntent": "duplicate_charge"
    },
    "b": {
      "n": 3,
      "failed": 1,
      "failureRate": 0.3333333333333333,
      "avgCostUsd": 0.004970349965667724,
      "totalCostUsd": 0.009940699931335449,
      "avgLatencyS": 5.651,
      "avgWordErrorRate": 0,
      "avgSttConfidence": null,
      "failoverCount": 0,
      "sampleTranscript": "Hi, I'm calling because I was charged twice for the same order. It's order 48213, and I was charged $47.99 both times. Could you please check the transaction and refund the duplicate charge?",
      "primaryIntent": "duplicate_charge"
    },
    "calls": [
      {
        "id": "f3397847-340f-4388-b8cd-fe49c0a6af05",
        "side": "A",
        "stt_provider_used": "deepgram",
        "failover": false,
        "predicted_category": "ok",
        "status": "completed",
        "total_cost_usd": "0.003580629166666667",
        "latency_s": 5.126,
        "wer": 0
      },
      {
        "id": "5c053f24-bd9c-48a4-b05f-6e42be5c185e",
        "side": "B",
        "stt_provider_used": "whisper",
        "failover": false,
        "predicted_category": "ok",
        "status": "completed",
        "total_cost_usd": "0.005128549965667724",
        "latency_s": 6.063,
        "wer": 0
      },
      {
        "id": "3570a9ad-485b-4252-bfe0-bbd3a8a18057",
        "side": "A",
        "stt_provider_used": "deepgram",
        "failover": false,
        "predicted_category": "ok",
        "status": "completed",
        "total_cost_usd": "0.003580629166666667",
        "latency_s": 3.83,
        "wer": 0
      },
      {
        "id": "e85d5579-b577-4b9e-9610-46191ab8af16",
        "side": "B",
        "stt_provider_used": "whisper",
        "failover": false,
        "predicted_category": "timeout",
        "status": "failed",
        "total_cost_usd": "0.005044349965667725",
        "latency_s": 11.122,
        "wer": 0
      },
      {
        "id": "d868709d-e3f5-4f91-b6e5-2b18b1da3e61",
        "side": "A",
        "stt_provider_used": "deepgram",
        "failover": false,
        "predicted_category": "ok",
        "status": "completed",
        "total_cost_usd": "0.0035824291666666673",
        "latency_s": 3.423,
        "wer": 0
      },
      {
        "id": "fd367a50-526e-4f14-aa88-56792aff1640",
        "side": "B",
        "stt_provider_used": "whisper",
        "failover": false,
        "predicted_category": "ok",
        "status": "completed",
        "total_cost_usd": "0.0048121499656677245",
        "latency_s": 5.239,
        "wer": 0
      }
    ],
    "metrics": [
      {
        "id": "failures",
        "label": "Failed calls",
        "a": 0,
        "b": 0.3333333333333333,
        "better": "none",
        "why": "A failed 0 of 3, B failed 1 of 3: too small a difference to count."
      },
      {
        "id": "accuracy",
        "label": "Transcript errors (word error rate)",
        "a": 0,
        "b": 0,
        "better": "none",
        "why": "A 0% vs B 0%: the gap is smaller than the 3% needed to count."
      },
      {
        "id": "speed",
        "label": "Pipeline time",
        "a": 4.126333333333333,
        "b": 5.651,
        "better": "A",
        "why": "A 4.1s vs B 5.7s, and every run of the better side beats every run of the other."
      },
      {
        "id": "cost",
        "label": "Cost per call",
        "a": 0.003581229166666667,
        "b": 0.004970349965667724,
        "better": "A",
        "why": "A $0.0036 vs B $0.0050, and every run of the better side beats every run of the other."
      }
    ]
  }
};
export const DEMO_CALLS = [
  {
    "id": "call-1-clean-baseline.wav",
    "label": "1 · Clean baseline",
    "group": "core",
    "category": "healthy",
    "level": 1,
    "speaker": null,
    "environment": null,
    "seconds": 15.4,
    "measured": {
      "wer": 0,
      "condition": "clean_wideband",
      "difficulty": "Easy",
      "speakers": 1,
      "intent": "duplicate_charge"
    }
  },
  {
    "id": "call-2-noisy-cafe.wav",
    "label": "2 · Noisy café",
    "group": "core",
    "category": "noisy",
    "level": 2,
    "speaker": null,
    "environment": null,
    "seconds": 11,
    "measured": {
      "wer": 18.5,
      "condition": "noisy",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "pending_transaction"
    }
  },
  {
    "id": "call-3-mumbled-unsure.wav",
    "label": "3 · Mumbled & unsure",
    "group": "core",
    "category": "mumbled",
    "level": 3,
    "speaker": null,
    "environment": null,
    "seconds": 17.5,
    "measured": {
      "wer": 15.6,
      "condition": "band_limited",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "duplicate_charge"
    }
  },
  {
    "id": "call-4-long-multi-detail.wav",
    "label": "4 · Long, multi-detail",
    "group": "core",
    "category": "long",
    "level": 4,
    "speaker": null,
    "environment": null,
    "seconds": 32.1,
    "measured": {
      "wer": 9.2,
      "condition": "band_limited",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "duplicate_charge"
    }
  },
  {
    "id": "call-5-failure-heavy-multi-intent.wav",
    "label": "5 · Failure-heavy, multi-intent",
    "group": "core",
    "category": "multi_intent",
    "level": 5,
    "speaker": null,
    "environment": null,
    "seconds": 20.6,
    "measured": {
      "wer": 16.4,
      "condition": "band_limited",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "duplicate_charge"
    }
  },
  {
    "id": "stress-01-young-male-clear-baseline.wav",
    "label": "S1 · Young male, clear baseline",
    "group": "stress",
    "category": "clear",
    "level": 1,
    "speaker": "Young adult male · fast · calm",
    "environment": "Clean studio-like recording, close microphone",
    "seconds": 12.9,
    "measured": {
      "wer": 2.9,
      "condition": "clean_wideband",
      "difficulty": "Easy",
      "speakers": 1,
      "intent": "refund_request"
    }
  },
  {
    "id": "stress-02-middle-aged-female-hesitant-forgets-order.wav",
    "label": "S2 · Middle-aged female, hesitant",
    "group": "stress",
    "category": "hesitant",
    "level": 3,
    "speaker": "Middle-aged female · slow · hesitant, embarrassed",
    "environment": "Quiet indoor room, audible breathing",
    "seconds": 35.1,
    "measured": {
      "wer": 0,
      "condition": "clean_wideband",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "missing_order"
    }
  },
  {
    "id": "stress-03-older-male-slow-noisy-repeats-amount.wav",
    "label": "S3 · Older male, slow, home noise",
    "group": "stress",
    "category": "noisy_slow",
    "level": 3,
    "speaker": "Older adult male · slow, slightly loud · patient",
    "environment": "Living room: distant TV chatter, occasional thumps and clinks",
    "seconds": 38.1,
    "measured": {
      "wer": 1.3,
      "condition": "noisy",
      "difficulty": "Hard",
      "speakers": 2,
      "intent": "incorrect_charge"
    }
  },
  {
    "id": "stress-04-young-female-fast-interruptions.wav",
    "label": "S4 · Young female, fast, interruptions",
    "group": "stress",
    "category": "interruptions",
    "level": 4,
    "speaker": "Young adult female · fast · impatient",
    "environment": "Open-plan office: subtle background conversation, keyboards, air conditioning",
    "seconds": 23.6,
    "measured": {
      "wer": 8.6,
      "condition": "noisy",
      "difficulty": "Severe",
      "speakers": 2,
      "intent": "pending_transaction"
    }
  },
  {
    "id": "stress-05-middle-aged-male-phone-static.wav",
    "label": "S5 · Middle-aged male, telephone + static",
    "group": "stress",
    "category": "telephone",
    "level": 3,
    "speaker": "Middle-aged male · calm, clear · tired",
    "environment": "Narrow-band telephone line with static crackle and compression",
    "seconds": 21.6,
    "measured": {
      "wer": 3.1,
      "condition": "degraded",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "incorrect_charge"
    }
  },
  {
    "id": "stress-06-young-female-busy-cafe-repeats.wav",
    "label": "S6 · Young female, busy café",
    "group": "stress",
    "category": "cafe",
    "level": 4,
    "speaker": "Young adult female · higher-pitched · rushed, distracted",
    "environment": "Busy café: chatter, cups, espresso hiss, a plate crash mid-sentence",
    "seconds": 26.7,
    "measured": {
      "wer": 0,
      "condition": "noisy",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "pending_transaction"
    }
  },
  {
    "id": "stress-07-older-female-confused-corrections.wav",
    "label": "S7 · Older female, confused, corrections",
    "group": "stress",
    "category": "corrections",
    "level": 4,
    "speaker": "Older adult female · soft, slow · calm but confused",
    "environment": "Quiet room with mild echo",
    "seconds": 40.8,
    "measured": {
      "wer": 4.8,
      "condition": "clean_wideband",
      "difficulty": "Moderate",
      "speakers": 1,
      "intent": "billing_account_issue"
    }
  },
  {
    "id": "stress-08-nervous-male-long-pauses-ambiguous.wav",
    "label": "S8 · Nervous male, long pauses, ambiguity",
    "group": "stress",
    "category": "ambiguity",
    "level": 4,
    "speaker": "Adult male · quiet, nervous, uncertain",
    "environment": "Intermittent bumps and horns over faint electronic hiss; uneven microphone distance",
    "seconds": 33.7,
    "measured": {
      "wer": 0,
      "condition": "acceptable",
      "difficulty": "Moderate",
      "speakers": 1,
      "intent": "pending_transaction"
    }
  },
  {
    "id": "stress-09-frustrated-female-multi-intent-street.wav",
    "label": "S9 · Frustrated female, four problems, street",
    "group": "stress",
    "category": "multi_intent",
    "level": 5,
    "speaker": "Adult female · higher-pitched · frustrated but composed",
    "environment": "Street: traffic swells, distant voices, a horn",
    "seconds": 42.2,
    "measured": {
      "wer": 3.6,
      "condition": "degraded",
      "difficulty": "Severe",
      "speakers": 2,
      "intent": "incorrect_charge"
    }
  },
  {
    "id": "stress-10-max-stress-train-phone-multi-issue.wav",
    "label": "S10 · Maximum stress: train, phone line",
    "group": "stress",
    "category": "maximum",
    "level": 5,
    "speaker": "Middle-aged male · deep, tired · stressed and rushed",
    "environment": "Moving train with announcement, engine rumble and a brake squeal, over a compressed phone line",
    "seconds": 53.1,
    "measured": {
      "wer": 4.1,
      "condition": "noisy",
      "difficulty": "Severe",
      "speakers": 2,
      "intent": "missing_order"
    }
  }
];
export const QUICK_CLIPS = 4;
