// GENERATED by backend/bench/build-reference.mjs from backend/bench/results/*.json. Do not edit by hand.
export const REFERENCE = {
  "measuredOn": "2026-09-30",
  "faults": {
    "sample": [
      "stress-03",
      "stress-07",
      "stress-09"
    ],
    "rows": [
      {
        "injected": "bad_stt",
        "predicted": [
          "bad_stt",
          "bad_stt",
          "bad_stt"
        ]
      },
      {
        "injected": "tts_glitch",
        "predicted": [
          "tts_glitch",
          "tts_glitch",
          "tts_glitch"
        ]
      },
      {
        "injected": "timeout",
        "predicted": [
          "timeout",
          "timeout",
          "timeout"
        ]
      },
      {
        "injected": "user_hangup",
        "predicted": [
          "user_hangup",
          "user_hangup",
          "user_hangup"
        ]
      },
      {
        "injected": "network_drop",
        "predicted": [
          "network_drop",
          "network_drop",
          "network_drop"
        ]
      },
      {
        "injected": "exception",
        "predicted": [
          "exception",
          "exception",
          "exception"
        ]
      },
      {
        "injected": "hallucination",
        "predicted": [
          "timeout",
          "ok",
          "timeout"
        ]
      }
    ]
  },
  "clean": {
    "n": 19,
    "ok": 18,
    "other": [
      {
        "id": "noisy-line",
        "predicted": "bad_stt"
      }
    ]
  },
  "cost": {
    "n": 19,
    "avgUsd": 0.004077368421052632,
    "minUsd": 0.00151,
    "maxUsd": 0.00674
  },
  "stages": [
    {
      "stage": "stt",
      "provider": "deepgram",
      "n": 155,
      "p50Ms": 805,
      "p95Ms": 1467,
      "maxMs": 1930
    },
    {
      "stage": "stt",
      "provider": "whisper",
      "n": 27,
      "p50Ms": 1210,
      "p95Ms": 2800,
      "maxMs": 3890
    },
    {
      "stage": "llm",
      "provider": "openai",
      "n": 182,
      "p50Ms": 1035,
      "p95Ms": 1834,
      "maxMs": 3835
    },
    {
      "stage": "tts",
      "provider": "openai",
      "n": 182,
      "p50Ms": 1718,
      "p95Ms": 2808,
      "maxMs": 3975
    }
  ],
  "costStages": [
    {
      "stage": "stt",
      "provider": "deepgram",
      "n": 155,
      "avgCostUsd": 0.0016593
    },
    {
      "stage": "llm",
      "provider": "openai",
      "n": 182,
      "avgCostUsd": 0.0000413
    },
    {
      "stage": "tts",
      "provider": "openai",
      "n": 182,
      "avgCostUsd": 0.0019381
    },
    {
      "stage": "analysis",
      "provider": "openai",
      "n": 142,
      "avgCostUsd": 0.0004077
    }
  ],
  "ab": {
    "sample": "call-1-clean-baseline.wav",
    "iterations": 3,
    "configA": {
      "llmModel": "gpt-4o-mini",
      "preferredSttProvider": "deepgram"
    },
    "configB": {
      "llmModel": "gpt-4o",
      "preferredSttProvider": "whisper"
    },
    "headline": "Config A is faster and cheaper, with no quality difference.",
    "winner": "A",
    "caveats": [],
    "a": {
      "n": 3,
      "failed": 0,
      "failureRate": 0,
      "avgCostUsd": 0.003581229166666667,
      "totalCostUsd": 0.010743687500000002,
      "avgLatencyS": 4.126333333333333,
      "avgWordErrorRate": 0,
      "avgSttConfidence": 0.9990160387878788,
      "failoverCount": 0,
      "sampleTranscript": "Hi. I'm calling because I was charged twice for the same order. It's order 48213, and I was charged $47.99 both times. Could you please check the transaction and refund the duplicate charge?",
      "primaryIntent": "duplicate_charge"
    },
    "b": {
      "n": 3,
      "failed": 1,
      "failureRate": 0.3333333333333333,
      "avgCostUsd": 0.004970349965667724,
      "totalCostUsd": 0.009940699931335449,
      "avgLatencyS": 5.651,
      "avgWordErrorRate": 0,
      "avgSttConfidence": null,
      "failoverCount": 0,
      "sampleTranscript": "Hi, I'm calling because I was charged twice for the same order. It's order 48213, and I was charged $47.99 both times. Could you please check the transaction and refund the duplicate charge?",
      "primaryIntent": "duplicate_charge"
    },
    "calls": [
      {
        "id": "f3397847-340f-4388-b8cd-fe49c0a6af05",
        "side": "A",
        "stt_provider_used": "deepgram",
        "failover": false,
        "predicted_category": "ok",
        "status": "completed",
        "total_cost_usd": "0.003580629166666667",
        "latency_s": 5.126,
        "wer": 0
      },
      {
        "id": "5c053f24-bd9c-48a4-b05f-6e42be5c185e",
        "side": "B",
        "stt_provider_used": "whisper",
        "failover": false,
        "predicted_category": "ok",
        "status": "completed",
        "total_cost_usd": "0.005128549965667724",
        "latency_s": 6.063,
        "wer": 0
      },
      {
        "id": "3570a9ad-485b-4252-bfe0-bbd3a8a18057",
        "side": "A",
        "stt_provider_used": "deepgram",
        "failover": false,
        "predicted_category": "ok",
        "status": "completed",
        "total_cost_usd": "0.003580629166666667",
        "latency_s": 3.83,
        "wer": 0
      },
      {
        "id": "e85d5579-b577-4b9e-9610-46191ab8af16",
        "side": "B",
        "stt_provider_used": "whisper",
        "failover": false,
        "predicted_category": "timeout",
        "status": "failed",
        "total_cost_usd": "0.005044349965667725",
        "latency_s": 11.122,
        "wer": 0
      },
      {
        "id": "d868709d-e3f5-4f91-b6e5-2b18b1da3e61",
        "side": "A",
        "stt_provider_used": "deepgram",
        "failover": false,
        "predicted_category": "ok",
        "status": "completed",
        "total_cost_usd": "0.0035824291666666673",
        "latency_s": 3.423,
        "wer": 0
      },
      {
        "id": "fd367a50-526e-4f14-aa88-56792aff1640",
        "side": "B",
        "stt_provider_used": "whisper",
        "failover": false,
        "predicted_category": "ok",
        "status": "completed",
        "total_cost_usd": "0.0048121499656677245",
        "latency_s": 5.239,
        "wer": 0
      }
    ],
    "metrics": [
      {
        "id": "failures",
        "label": "Failed calls",
        "a": 0,
        "b": 0.3333333333333333,
        "better": "none",
        "why": "A failed 0 of 3, B failed 1 of 3: too small a difference to count."
      },
      {
        "id": "accuracy",
        "label": "Transcript errors (word error rate)",
        "a": 0,
        "b": 0,
        "better": "none",
        "why": "A 0% vs B 0%: the gap is smaller than the 3% needed to count."
      },
      {
        "id": "speed",
        "label": "Pipeline time",
        "a": 4.126333333333333,
        "b": 5.651,
        "better": "A",
        "why": "A 4.1s vs B 5.7s, and every run of the better side beats every run of the other."
      },
      {
        "id": "cost",
        "label": "Cost per call",
        "a": 0.003581229166666667,
        "b": 0.004970349965667724,
        "better": "A",
        "why": "A $0.0036 vs B $0.0050, and every run of the better side beats every run of the other."
      }
    ]
  }
};
export const DEMO_CALLS = [
  {
    "id": "call-1-clean-baseline.wav",
    "label": "1 · Clean baseline",
    "group": "core",
    "category": "healthy",
    "level": 1,
    "speaker": null,
    "environment": null,
    "tags": [],
    "summary": "Clear duplicate-charge refund request. One intent, no noise.",
    "challenge": "Healthy baseline: clear speech, complete sentences, one intent, no background noise.",
    "says": "Hi, I'm calling because I was charged twice for the same order. It's order 4 8 2 1 3, and I was charged forty-seven dollars and ninety-nine cents both times. Could you please check the transaction and refund the duplicate charge?",
    "seconds": 15.4,
    "measured": {
      "wer": 0,
      "condition": "clean_wideband",
      "difficulty": "Easy",
      "speakers": 1,
      "intent": "duplicate_charge"
    }
  },
  {
    "id": "call-2-noisy-cafe.wav",
    "label": "2 · Noisy café",
    "group": "core",
    "category": "noisy",
    "level": 2,
    "speaker": null,
    "environment": null,
    "tags": [],
    "summary": "Payment deducted but order still pending, from a busy café with traffic outside.",
    "challenge": "Environmental degradation: speech is clear but sits over café chatter, traffic and clatter, with uneven volume.",
    "says": "Hey, I'm calling about my payment. The money was deducted, about sixty-two dollars, but my order still says pending. It's order 7 3 9 0 5. Can you help me with this?",
    "seconds": 11,
    "measured": {
      "wer": 18.5,
      "condition": "noisy",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "pending_transaction"
    }
  },
  {
    "id": "call-3-mumbled-unsure.wav",
    "label": "3 · Mumbled & unsure",
    "group": "core",
    "category": "mumbled",
    "level": 3,
    "speaker": null,
    "environment": null,
    "tags": [],
    "summary": "Confused customer who thinks they were charged twice but is not sure.",
    "challenge": "Speaking style: fillers, restarts, pauses, uncertainty and a self-corrected amount, quietly spoken.",
    "says": "Uh, yeah, so... basically, I paid for the order yesterday, but... um, I think the payment went through twice? Maybe. I'm not... I'm not completely sure what happened. Wait, let me check. It says forty... no, forty-eight something? I believe. I just don't want to pay twice.",
    "seconds": 17.5,
    "measured": {
      "wer": 15.6,
      "condition": "band_limited",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "duplicate_charge"
    }
  },
  {
    "id": "call-4-long-multi-detail.wav",
    "label": "4 · Long, multi-detail",
    "group": "core",
    "category": "long",
    "level": 4,
    "speaker": null,
    "environment": null,
    "tags": [],
    "summary": "Failed payment, retry, a possible double charge, a wrong amount and a wrong order number, all corrected mid-call.",
    "challenge": "Context over time: details spread across the call, corrected amount and order number, repetition, a prior support contact and a final request.",
    "says": "Hi, I placed an order five days ago, and the payment failed the first time, so I tried again. But my banking app shows I was charged twice, forty-three fifty each. Actually, wait... let me check that. Sorry, I gave you the wrong amount. It's fifty-three forty each. The order number is 6 1 8 4 2. No, sorry, 6 1 8 2 4. I contacted support last week and nothing happened, and the order still says processing. Did you get all that? Please look into the duplicate charge, and refund it if it's real.",
    "seconds": 32.1,
    "measured": {
      "wer": 9.2,
      "condition": "band_limited",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "duplicate_charge"
    }
  },
  {
    "id": "call-5-failure-heavy-multi-intent.wav",
    "label": "5 · Failure-heavy, multi-intent",
    "group": "core",
    "category": "multi_intent",
    "level": 5,
    "speaker": null,
    "environment": null,
    "tags": [],
    "summary": "Duplicate charge, an ambiguous failed/pending first payment, a missing order and an unknown fee, from a frustrated customer.",
    "challenge": "Reasoning load: six related intents, conflicting payment state (failed vs pending), unclear which charge matches which attempt, and an unrecognised fee.",
    "says": "Okay, I was charged twice. That's the part I don't understand. I thought the first payment failed, so I tried again, and the second one went through. But my banking app shows the first one as pending. So did it fail or not? And the order, 9 2 6 7 1, still hasn't arrived, and there's another fee I don't recognize, eight fifty. I just want to know what actually happened, and get the extra money back.",
    "seconds": 20.6,
    "measured": {
      "wer": 16.4,
      "condition": "band_limited",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "duplicate_charge"
    }
  },
  {
    "id": "stress-01-young-male-clear-baseline.wav",
    "label": "S1 · Young male, clear baseline",
    "group": "stress",
    "category": "clear",
    "level": 1,
    "speaker": "Young adult male · fast · calm",
    "environment": "Clean studio-like recording, close microphone",
    "tags": [
      "Fast speech",
      "Single intent",
      "No noise"
    ],
    "summary": "Cancelled subscription still billed. One simple request, fast but very clear.",
    "challenge": "A second clean baseline with a different voice: should transcribe almost perfectly and read as a single, simple intent.",
    "says": "Hi there. I'm calling because I was billed for a premium subscription that I cancelled last month. The reference on the invoice is 3 1 0 7 4, and the charge was nineteen dollars ninety-nine. Could you please refund it?",
    "seconds": 12.9,
    "measured": {
      "wer": 2.9,
      "condition": "clean_wideband",
      "difficulty": "Easy",
      "speakers": 1,
      "intent": "refund_request"
    }
  },
  {
    "id": "stress-02-middle-aged-female-hesitant-forgets-order.wav",
    "label": "S2 · Middle-aged female, hesitant",
    "group": "stress",
    "category": "hesitant",
    "level": 3,
    "speaker": "Middle-aged female · slow · hesitant, embarrassed",
    "environment": "Quiet indoor room, audible breathing",
    "tags": [
      "Fillers (um/uh)",
      "Long pause",
      "Sentence restart",
      "Self-correction",
      "Forgets then recalls order number"
    ],
    "summary": "Missing order. She forgets the order number, pauses to find it, and corrects the delivery day.",
    "challenge": "Hesitation, a 3-second pause before a number, a restarted sentence and a corrected date (Tuesday to Wednesday). Tests entity extraction after a pause.",
    "says": "Um, hi. I'm calling about, uh, an order that hasn't arrived. It was supposed to be here on Tuesday... no, wait, sorry, it was Wednesday. And I was, I was hoping you could... I mean, could you check where it is? The order number is... um... hold on, I had it written down somewhere. Okay, sorry. It's 5 2 9 1 8. Yes, 5 2 9 1 8. Thank you. I'm sorry, I'm terrible with these things.",
    "seconds": 35.1,
    "measured": {
      "wer": 0,
      "condition": "clean_wideband",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "missing_order"
    }
  },
  {
    "id": "stress-03-older-male-slow-noisy-repeats-amount.wav",
    "label": "S3 · Older male, slow, home noise",
    "group": "stress",
    "category": "noisy_slow",
    "level": 3,
    "speaker": "Older adult male · slow, slightly loud · patient",
    "environment": "Living room: distant TV chatter, occasional thumps and clinks",
    "tags": [
      "Slow speech",
      "Distant chatter",
      "Repeats key detail",
      "Agent asks to repeat",
      "Unsure about charge"
    ],
    "summary": "A charge he does not recognise. He repeats the amount because he thinks the agent did not catch it.",
    "challenge": "Slow elderly speech over TV chatter with occasional thumps, deliberate repetition of the amount, and honest uncertainty about who made the purchase.",
    "says": "Customer: Hello? Yes, hello. There is a charge on my card that I do not recognise.\nCustomer: It is for twenty-nine dollars and ninety-five cents. From some company I cannot read.\nAgent: I'm sorry, could you repeat the amount for me?\nCustomer: Twenty-nine... ninety-five. Twenty-nine dollars, ninety-five cents. Did you get that?\nAgent: Got it, thank you. And when did it appear?\nCustomer: Oh, it was on, let me think, last Friday I believe. I did not buy anything. Maybe it is my grandson, I am not sure.",
    "seconds": 38.1,
    "measured": {
      "wer": 1.3,
      "condition": "noisy",
      "difficulty": "Hard",
      "speakers": 2,
      "intent": "incorrect_charge"
    }
  },
  {
    "id": "stress-04-young-female-fast-interruptions.wav",
    "label": "S4 · Young female, fast, interruptions",
    "group": "stress",
    "category": "interruptions",
    "level": 4,
    "speaker": "Young adult female · fast · impatient",
    "environment": "Open-plan office: subtle background conversation, keyboards, air conditioning",
    "tags": [
      "Fast speech",
      "Talks over the agent",
      "Agent interrupts",
      "'Sorry, go ahead'",
      "Self-correction (49 to 59)"
    ],
    "summary": "Payment stuck pending. She talks over the agent, apologises, then cuts in again.",
    "challenge": "Real speech overlap between two speakers, quick turn-taking, an impatient tone and a corrected amount ($49 to $59) in the middle of an interruption.",
    "says": "Agent: Thank you for calling support. Before we begin I'll need to verify a few details, starting with—\nCustomer: Yeah, yeah, my order's 8 4 1 6 0, I paid forty-nine dollars... sorry, fifty-nine dollars, and it still says pending.\nAgent: Okay, and can you confirm the name on the—\nCustomer: Sorry, go ahead.\nAgent: I just need the name on the account, please.\nCustomer: It's Jordan Lee. Can we please just fix the payment?\nAgent: Absolutely. Let me look into it now.",
    "seconds": 23.6,
    "measured": {
      "wer": 8.6,
      "condition": "noisy",
      "difficulty": "Severe",
      "speakers": 2,
      "intent": "pending_transaction"
    }
  },
  {
    "id": "stress-05-middle-aged-male-phone-static.wav",
    "label": "S5 · Middle-aged male, telephone + static",
    "group": "stress",
    "category": "telephone",
    "level": 3,
    "speaker": "Middle-aged male · calm, clear · tired",
    "environment": "Narrow-band telephone line with static crackle and compression",
    "tags": [
      "Telephone quality",
      "Static/compression",
      "Transaction number",
      "Monetary amount"
    ],
    "summary": "Incorrect charge: authorised $82 but billed $128.50. Clear speech over a poor phone line.",
    "challenge": "Telephone band-limiting and crackle can hide digits in the transaction number and the two amounts.",
    "says": "Good afternoon. I'm calling about an incorrect charge on my account. The transaction number is 7 7 4 0 2 1, and the amount was one hundred twenty-eight dollars fifty. I only authorised eighty-two dollars, so I'd like the difference refunded.",
    "seconds": 21.6,
    "measured": {
      "wer": 3.1,
      "condition": "degraded",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "incorrect_charge"
    }
  },
  {
    "id": "stress-06-young-female-busy-cafe-repeats.wav",
    "label": "S6 · Young female, busy café",
    "group": "stress",
    "category": "cafe",
    "level": 4,
    "speaker": "Young adult female · higher-pitched · rushed, distracted",
    "environment": "Busy café: chatter, cups, espresso hiss, a plate crash mid-sentence",
    "tags": [
      "Café noise",
      "Sudden loud noise",
      "Repeats a sentence",
      "Higher voice",
      "Pending payment"
    ],
    "summary": "Payment pending for two days. A loud crash cuts her off and she has to repeat herself.",
    "challenge": "Continuous café ambience plus one sudden crash that masks part of a sentence, followed by a repeated sentence.",
    "says": "Hi, sorry, it's really loud in here. I'm calling about a payment that's been pending for two days. It says pending in my banking app but the order still hasn't— sorry, hold on. Sorry. The order still hasn't shipped. I said, the order still hasn't shipped. It's order 6 6 0 3 7, and the amount was thirty-six seventy.",
    "seconds": 26.7,
    "measured": {
      "wer": 0,
      "condition": "noisy",
      "difficulty": "Hard",
      "speakers": 1,
      "intent": "pending_transaction"
    }
  },
  {
    "id": "stress-07-older-female-confused-corrections.wav",
    "label": "S7 · Older female, confused, corrections",
    "group": "stress",
    "category": "corrections",
    "level": 4,
    "speaker": "Older adult female · soft, slow · calm but confused",
    "environment": "Quiet room with mild echo",
    "tags": [
      "Wrong date then corrected",
      "Wrong amount then corrected",
      "Forgets order number",
      "Reverb/echo"
    ],
    "summary": "Billing problem. She corrects the date and the amount, forgets the order number, then states everything clearly.",
    "challenge": "The system must keep the corrected values (14 March, $46.80, order 20759) and drop the first, wrong ones (12th, $48).",
    "says": "Hello, dear. I think there's a problem with my bill. I was charged on the twelfth of March... oh, no, the fourteenth. Yes, the fourteenth. It was forty-eight dollars... no, sorry, forty-six eighty. That's right, forty-six eighty. And my order number, oh, I've forgotten it. Give me a moment. Yes. It's 2 0 7 5 9. Two, oh, seven, five, nine. That's the one. So the fourteenth, forty-six eighty, order 2 0 7 5 9.",
    "seconds": 40.8,
    "measured": {
      "wer": 4.8,
      "condition": "clean_wideband",
      "difficulty": "Moderate",
      "speakers": 1,
      "intent": "billing_account_issue"
    }
  },
  {
    "id": "stress-08-nervous-male-long-pauses-ambiguous.wav",
    "label": "S8 · Nervous male, long pauses, ambiguity",
    "group": "stress",
    "category": "ambiguity",
    "level": 4,
    "speaker": "Adult male · quiet, nervous, uncertain",
    "environment": "Intermittent bumps and horns over faint electronic hiss; uneven microphone distance",
    "tags": [
      "Long pauses (2-3 s)",
      "Nervous",
      "Failed vs pending unclear",
      "Intermittent noise",
      "Broadband hiss"
    ],
    "summary": "He is not sure whether his payment failed or is pending, and says so.",
    "challenge": "A careful system must NOT claim the payment failed or succeeded: the customer never established it. Long pauses and quiet speech add transcription risk.",
    "says": "Um, hi. So, I made a payment yesterday... And I thought it failed, because it showed an error at first. Actually, I'm not completely sure. Let me check. Okay. On my banking app it just says pending. So, maybe it didn't fail? I don't know. I don't want to pay twice, though. Could you tell me which it is?",
    "seconds": 33.7,
    "measured": {
      "wer": 0,
      "condition": "acceptable",
      "difficulty": "Moderate",
      "speakers": 1,
      "intent": "pending_transaction"
    }
  },
  {
    "id": "stress-09-frustrated-female-multi-intent-street.wav",
    "label": "S9 · Frustrated female, four problems, street",
    "group": "stress",
    "category": "multi_intent",
    "level": 5,
    "speaker": "Adult female · higher-pitched · frustrated but composed",
    "environment": "Street: traffic swells, distant voices, a horn",
    "tags": [
      "Frustrated",
      "Agent interrupted",
      "Repeats an issue",
      "Corrects order number",
      "Four related problems"
    ],
    "summary": "Wrong charge, missing order, a possible duplicate payment and an extra fee, revealed one by one.",
    "challenge": "Multi-intent handling over traffic noise: issues arrive gradually, one is repeated, the order number is corrected (4821 to 4917), and she interrupts the agent once.",
    "says": "Customer: Hi. I've been charged for something I didn't order, and honestly I'm pretty fed up.\nAgent: I'm sorry to hear that. Let me pull up your account and—\nCustomer: It's twenty-two ninety-nine, it came out on Monday.\nCustomer: And that's not all. My order number is 4821... wait, that's the old one. The current order is 4917, and it never showed up.\nCustomer: I think I was also charged twice for it, because my bank shows two payments.\nCustomer: And there's an extra fee of six dollars that I don't recognise.\nCustomer: Like I said, I was charged for something I didn't order.\nCustomer: I just want the wrong charge reversed and someone to tell me where my order is.",
    "seconds": 42.2,
    "measured": {
      "wer": 3.6,
      "condition": "degraded",
      "difficulty": "Severe",
      "speakers": 2,
      "intent": "incorrect_charge"
    }
  },
  {
    "id": "stress-10-max-stress-train-phone-multi-issue.wav",
    "label": "S10 · Maximum stress: train, phone line",
    "group": "stress",
    "category": "maximum",
    "level": 5,
    "speaker": "Middle-aged male · deep, tired · stressed and rushed",
    "environment": "Moving train with announcement, engine rumble and a brake squeal, over a compressed phone line",
    "tags": [
      "Moderate noise",
      "Phone compression",
      "Interruption + overlap",
      "Correction",
      "Contradiction",
      "Late detail",
      "Multiple issues"
    ],
    "summary": "Missing order, a possible double payment and a refund, from a moving train.",
    "challenge": "Everything at once: transit noise and a brake squeal, a compressed line, hesitation, an overlap, an interruption, a corrected order number, a contradictory payment status, and a key detail (the card belongs to his wife) revealed last.",
    "says": "Customer: Yeah, hi... uh, I'm on the train so, sorry if it cuts out.\nCustomer: I ordered a phone case... two phone cases, sorry, three, last week, and it never arrived.\nAgent: I can help with that. Can I get the order number, please?\nCustomer: Yeah, it's, um, 3 8 5 2 0... well, hang on.\nCustomer: Sorry. 3 8 5 2 0. No wait, that's the old one. 3 8 5 0 2.\nAgent: Thanks. I can see a payment of forty-one dollars, and—\nCustomer: And I got charged twice for it, I think.\nCustomer: The, uh, the first payment failed, but then the bank shows both as pending, so... I don't know.\nCustomer: Oh, and I forgot, the card is my wife's card, not mine. Does that matter?\nCustomer: So, yeah, I need to know where the order is and I want the extra payment back.",
    "seconds": 53.1,
    "measured": {
      "wer": 4.1,
      "condition": "noisy",
      "difficulty": "Severe",
      "speakers": 2,
      "intent": "missing_order"
    }
  },
  {
    "id": "refund-request.wav",
    "label": "Refund request (quick test)",
    "group": "quick",
    "category": "healthy",
    "level": 1,
    "speaker": null,
    "environment": null,
    "tags": [],
    "summary": "Short clean clip.",
    "challenge": "Short clean clip for quick tests.",
    "says": "Hi, I was charged twice on my last invoice and I would like a refund please.",
    "seconds": 5.5,
    "measured": null
  },
  {
    "id": "book-table.wav",
    "label": "Book a table (quick test)",
    "group": "quick",
    "category": "healthy",
    "level": 1,
    "speaker": null,
    "environment": null,
    "tags": [],
    "summary": "Short clean clip.",
    "challenge": "Short clean clip for quick tests.",
    "says": "Book me a table for two at seven pm tonight.",
    "seconds": 3.1,
    "measured": null
  },
  {
    "id": "weather-today.wav",
    "label": "Weather question (quick test)",
    "group": "quick",
    "category": "healthy",
    "level": 1,
    "speaker": null,
    "environment": null,
    "tags": [],
    "summary": "Short clean clip.",
    "challenge": "Short clean clip for quick tests.",
    "says": "What's the weather going to be like today?",
    "seconds": 2.8,
    "measured": null
  },
  {
    "id": "noisy-line.wav",
    "label": "Noisy line (quick test)",
    "group": "quick",
    "category": "noisy",
    "level": 2,
    "speaker": null,
    "environment": null,
    "tags": [],
    "summary": "Short clip, fast voice over static.",
    "challenge": "Short noisy clip for quick tests.",
    "says": "Uh, hi, I need to check my, uh, account balance. (with static)",
    "seconds": 3.4,
    "measured": null
  }
];
export const QUICK_CLIPS = 4;
